### ISSUE TITLE
Manually edit names of unrecognised Subjects

### ISSUE THREAD

**Issue by SreejithNS** [GDGVIT/vitty-app#12]
**Is your feature request related to a problem? Please describe.**
When I try to upload the Screenshot of my timetable, few subjects get its name automatically but few remains blank or null. I thought this might default to the subject code but it didn't, instead shows blank subject name everywhere.

**Describe the solution you'd like**
Please provide a edit button to alter the subject names in null or blank fields.

**Describe alternatives you've considered**
I couldn't find any alternative workarounds in the current release.

**Additional context**
![image](https://user-images.githubusercontent.com/28445535/128304174-0229a2c8-bde5-44ef-aa1b-302eeeb12421.png)

#### Will you be working on this feature?
- [ ] Yes
- [x] No

#### Have you talked with any inner-core member regarding this feature?
- [ ] Yes
- [x] No

**Comment by BRO3886** [comment]
There is an edit button on the extension before you press done

**Comment by BRO3886** [comment]
![image](https://user-images.githubusercontent.com/39856034/128315743-8d0ead6c-7743-4ba4-93f0-9353cb48a5b3.png)

On pressing Edit:
![image](https://user-images.githubusercontent.com/39856034/128315748-c29737e4-5d65-47ef-aa58-bb0797c5f43b.png)

**Comment by VisheshBansal** [comment]
@SreejithNS could you please open the issue on 
https://github.com/GDGVIT/vitty-extension as well?

**Comment by SreejithNS** [comment]
But the Edit button says to enter the slots details(as in VTOP Timetable) right? There is no provision to enter Custom Subject Name for unidentified subjects, is there?

I also checked the source code, I didn't find any SWEXXXX subject codes listed.

In my scenario it recognised everything correctly, the slot, the timing, the code, but not the subject name for few subjects.
