### ISSUE TITLE
Dim classes which are over

### ISSUE THREAD

**Issue by BRO3886** [GDGVIT/vitty-app#13]
see [this](https://github.com/GDGVIT/vitty-extension/issues/15)

**Comment by iamyajat** [comment]
I feel highlighting the current/ upcoming class would be better.
Something like this:
![image](https://user-images.githubusercontent.com/68477362/128396291-aa97df09-6261-41c4-9d09-4773be32f98a.png)
What do you think @BRO3886?

**Comment by BRO3886** [comment]
Yes looks much better
