### ISSUE TITLE
Request to adjust the notifications to different timezones

### ISSUE THREAD

**Issue by amlfarhad** [GDGVIT/vitty-app#16]
As someone who lives in the GCC, the notification feature of this app is useless for me as I get the notifications 1.5 hours after I'm supposed to get it, as all the times are in IST. It would be helpful if the time would be converted from IST to whatever the system's time zone is.

**Comment by iamyajat** [comment]
Hey, this issue has been fixed.
Update the extension and the app to the latest version and then reupload the timetable.
Cheers!

**Comment by amlfarhad** [comment]
Thank you so much! It works now.
