### ISSUE TITLE
Subjects not being shown even after adding in text format.

### ISSUE THREAD

**Issue by GauravPoosarla** [GDGVIT/vitty-app#19]
**Describe the bug**
I tried adding the subject list after copying from vtop. After adding one of my course is being skipped and not being shown in the final timetable. I tried manually as well but it resets the timetable to zero.

**Details**
Email ID:
poosarlagaurav@gmail.com

My timetable: 
![image](https://user-images.githubusercontent.com/59747089/152779211-9bce1bbc-34e2-4ef5-9dcf-f5bee042cb18.png)

After copying the text from vtop and pasting on the website. I have CSE1001 in L35+L36 on Monday but you can see in the following attached image that it is missing.
![image](https://user-images.githubusercontent.com/59747089/152779517-0942a6c8-81ed-4905-b9f1-0eacb1b531f7.png)

In the next step there was an option to add it manually I tried in the following way.
![image](https://user-images.githubusercontent.com/59747089/152779688-c9a744e0-b6ec-456a-8a86-24643a396dbf.png)

After I click on confirm it resets the complete timetable.
![image](https://user-images.githubusercontent.com/59747089/152779758-79bb1af7-0f27-4c90-b05b-62206344e46a.png)

Timetable in text format: For testing purposes

THEORY  Start  08:00  09:00  10:00  11:00  12:00  -  Lunch  14:00  15:00  16:00  17:00  18:00  18:51  19:01
End  08:50  09:50  10:50  11:50  12:50  -  Lunch  14:50  15:50  16:50  17:50  18:50  19:00  19:50
LAB  Start  08:00  08:51  09:51  10:41  11:40  12:31  Lunch  14:00  14:51  15:51  16:41  17:40  18:31  -
End  08:50  09:40  10:40  11:30  12:30  13:20  Lunch  14:50  15:40  16:40  17:30  18:30  19:20  -
MON  THEORY  A1-CBS3009-TH-SJT423-ALL  F1-MGT4004-TH-SJT424-ALL  D1-CBS3012-ETH-SJT202-ALL  TB1-HUM1046-TH-SJT602-ALL  TG1  -  Lunch  A2  F2  D2  TB2  TG2  -  V3
LAB  L1  L2  L3  L4  L5  L6  Lunch  L31  L32  L33  L34  L35-CSE1001-LO-MGB107 A-ALL  L36-CSE1001-LO-MGB107 A-ALL  -
TUE  THEORY  B1-HUM1046-TH-SJT602-ALL  G1  E1-CBS3008-ETH-MB312-ALL  TC1-CBS3014-ETH-MGB305-ALL  TAA1  -  Lunch  B2  G2  E2  TC2  TAA2  -  V4
LAB  L7  L8  L9  L10  L11  L12  Lunch  L37-CSE1001-LO-MGB107 A-ALL  L38-CSE1001-LO-MGB107 A-ALL  L39  L40  L41  L42  -
WED  THEORY  C1-CBS3014-ETH-MGB305-ALL  A1-CBS3009-TH-SJT423-ALL  F1-MGT4004-TH-SJT424-ALL  V1  V2  -  Lunch  C2  A2  F2  TD2  TBB2  -  V5
LAB  L13  L14  L15  L16  L17  L18  Lunch  L43  L44  L45-CSE1001-LO-MGB107 A-ALL  L46-CSE1001-LO-MGB107 A-ALL  L47-CBS3014-ELA-SJT516-ALL  L48-CBS3014-ELA-SJT516-ALL  -
THU  THEORY  D1-CBS3012-ETH-SJT202-ALL  B1-HUM1046-TH-SJT602-ALL  G1  TE1-CBS3008-ETH-MB312-ALL  TCC1  -  Lunch  D2  B2  G2  TE2  TCC2  -  V6
LAB  L19  L20  L21  L22  L23  L24  Lunch  L49  L50  L51  L52  L53-CBS3008-ELA-SJT515-ALL  L54-CBS3008-ELA-SJT515-ALL  -
FRI  THEORY  E1-CBS3008-ETH-MB312-ALL  C1-CBS3014-ETH-MGB305-ALL  TA1-CBS3009-TH-SJT423-ALL  TF1-MGT4004-TH-SJT424-ALL  TD1  -  Lunch  E2  C2  TA2  TF2  TDD2  -  V7
LAB  L25  L26  L27  L28  L29  L30  Lunch  L55  L56  L57-CBS3012-ELA-SJT621-ALL  L58-CBS3012-ELA-SJT621-ALL  L59  L60  -
SAT  THEORY  V8  X11  X12  Y11  Y12  -  Lunch  X21  Z21  Y21  W21  W22  -  V9
LAB  L71  L72  L73  L74  L75  L76  Lunch  L77  L78  L79  L80  L81  L82  -
SUN  THEORY  V10  Y11  Y12  X11  X12  -  Lunch  Y21  Z21  X21  W21  W22  -  V11
LAB  L83  L84  L85  L86  L87  L88  Lunch  L89  L90  L91  L92  L93  L94  -

**Expected behavior**
CSE1001 should be shown on Monday, Tuesday, Wednesday but it isn't being shown. I would be really grateful if you could do the needful.

**Comment by dk-a-dev** [comment]
old issue, resolved
