### ISSUE TITLE
Feature: Display Lab courses as courseName + Lab

### ISSUE THREAD

**Issue by 1407arjun** [GDGVIT/vitty-app#21]
**Is your feature request related to a problem? Please describe.**
Not a problem actually, but an enhancement. Notifications can be more specific in case of a lab, we do not know if its a reminder for a lab or a theory lecture. 

**Describe the solution you'd like**
Depending on the slot, we could append a "Lab" to the end of the course name, if the slot is a lab slot.

#### Will you be working on this feature?
- [x] Yes
- [ ] No

#### Have you talked with any inner-core member regarding this feature?
- [ ] Yes
- [x] No

**Comment by iamyajat** [comment]
Hey @1407arjun, 

There's a problem with this approach of additing Lab blindly at the end of a course name and that is that some courses have the word "Lab" in the course name itself.

For example, "Calculus Lab". If we use this method, the course name would become "Calculus Lab Lab".

**Comment by 1407arjun** [comment]
> 

Yeah so I have a solution for this. The problem that you have mentioned occurs for the current first year students since their curriculum is different. We can differentiate that by checking for the course code, since all the courses in the new curriculum are of length 8 and of length 7 in the old one.

**Comment by Kiddu77** [comment]
We can easily eliminate that by checking if the course has a time for 1hr 40 min and if there is a 'Lab' in their name dont add lab if there isn't add lab

**Comment by dk-a-dev** [comment]
closing as an old issue
