### ISSUE TITLE
Course title not loading 

### ISSUE THREAD

**Issue by Armaan-Indani** [GDGVIT/vitty-app#27]
For some EEE/ECE courses, the name is not shown on the app. Instead the course code is shown.
eg BEEE303L, BEEE202L

**Comment by dk-a-dev** [comment]
Try re-setting your vitty app again
- Go to https://vitty.dscvit.com/
- Login and re-paste ur time table from vtop

Le me know if its fixed @Armaan-Indani

**Comment by Armaan-Indani** [comment]
Yes it's fixed
Thanks a lot

**Comment by Armaan-Indani** [comment]
Please resolve the same for 
BCSE205L Computer Architecture and Organization 
BCSE203E Web Programming

**Comment by dk-a-dev** [comment]
@Armaan-Indani Sure bud will look into this issue

**Comment by dk-a-dev** [comment]
issue resolved
