### ISSUE TITLE
Wrong class time

### ISSUE THREAD

**Issue by 5EBIN** [GDGVIT/vitty-app#28]
**Describe the bug**
Class Timings are wrong even after updating multiple times

**To Reproduce**
1. Copied timetable and pasted as shown in VITTY
2.  Classes starts from 6.30 A.M.

**Expected behavior**
Classes should start from 8 A.M.

**Comment by dk-a-dev** [comment]
@5EBIN With the new update this issue is now resolved, we will close ur issue
