### ISSUE TITLE
Edit Timetable stuck on loading

### ISSUE THREAD

**Issue by MayankMangipudi** [GDGVIT/vitty-app#29]
**Unable To Add New Timetable**
after the beginning of the new semester, went into edit timetable and pasted the timetable from vtop starting from THEORY to L94.
Once doing so the website is stuck on a constant loading loop both on PC and Mobile.

**ACCOUNT**
Email: 
mayank.mangipudi@gmail.com

Timetable copied:
THEORY | Start | 08:00 | 09:00 | 10:00 | 11:00 | 12:00 | - | Lunch | 14:00 | 15:00 | 16:00 | 17:00 | 18:00 | 18:51 | 19:01
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
End | 08:50 | 09:50 | 10:50 | 11:50 | 12:50 | - | Lunch | 14:50 | 15:50 | 16:50 | 17:50 | 18:50 | 19:00 | 19:50
LAB | Start | 08:00 | 08:51 | 09:51 | 10:41 | 11:40 | 12:31 | Lunch | 14:00 | 14:51 | 15:51 | 16:41 | 17:40 | 18:31 | -
End | 08:50 | 09:40 | 10:40 | 11:30 | 12:30 | 13:20 | Lunch | 14:50 | 15:40 | 16:40 | 17:30 | 18:30 | 19:20 | -
MON | THEORY | A1-BCSE204L-TH-SJT305-ALL | F1 | D1-BCSE205L-TH-PRP304-ALL | TB1-BCSE306L-TH-SJT409-ALL | TG1-BMAT202L-TH-SJT305-ALL | - | Lunch | A2 | F2 | D2 | TB2 | TG2 | - | V3
LAB | L1 | L2 | L3 | L4 | L5 | L6 | Lunch | L31-BCSE203E-ELA-SJT121-ALL | L32-BCSE203E-ELA-SJT121-ALL | L33 | L34 | L35 | L36 | -
TUE | THEORY | B1-BCSE306L-TH-SJT409-ALL | G1-BMAT202L-TH-SJT305-ALL | E1-BSTS102P-SS-SJT304-ALL | TC1-BHUM203L-TH-PRP214-ALL | TAA1-BCSE203E-ETH-PRP207-ALL | - | Lunch | B2 | G2 | E2 | TC2 | TAA2 | - | V4
LAB | L7 | L8 | L9 | L10 | L11 | L12 | Lunch | L37-BCSE203E-ELA-SJT121-ALL | L38-BCSE203E-ELA-SJT121-ALL | L39 | L40 | L41 | L42 | -
WED | THEORY | C1-BHUM203L-TH-PRP214-ALL | A1-BCSE204L-TH-SJT305-ALL | F1 | V1 | V2 | - | Lunch | C2 | A2 | F2 | TD2 | TBB2 | - | V5
LAB | L13 | L14 | L15 | L16 | L17 | L18 | Lunch | L43 | L44 | L45 | L46 | L47 | L48 | -
THU | THEORY | D1-BCSE205L-TH-PRP304-ALL | B1-BCSE306L-TH-SJT409-ALL | G1-BMAT202L-TH-SJT305-ALL | TE1-BSTS102P-SS-SJT304-ALL | TCC1 | - | Lunch | D2 | B2 | G2 | TE2 | TCC2 | - | V6
LAB | L19 | L20 | L21 | L22 | L23 | L24 | Lunch | L49 | L50 | L51-BCSE204P-LO-SJT418-ALL | L52-BCSE204P-LO-SJT418-ALL | L53 | L54 | -
FRI | THEORY | E1-BSTS102P-SS-SJT304-ALL | C1-BHUM203L-TH-PRP214-ALL | TA1-BCSE204L-TH-SJT305-ALL | TF1 | TD1-BCSE205L-TH-PRP304-ALL | - | Lunch | E2 | C2 | TA2 | TF2 | TDD2 | - | V7
LAB | L25 | L26 | L27 | L28 | L29 | L30 | Lunch | L55 | L56 | L57-BMAT202P-LO-SJT319-ALL | L58-BMAT202P-LO-SJT319-ALL | L59 | L60 | -
SAT | THEORY | V8 | X11 | X12 | Y11 | Y12 | - | Lunch | X21 | Z21 | Y21 | W21 | W22 | - | V9
LAB | L71 | L72 | L73 | L74 | L75 | L76 | Lunch | L77 | L78 | L79 | L80 | L81 | L82 | -
SUN | THEORY | V10 | Y11 | Y12 | X11 | X12 | - | Lunch | Y21 | Z21 | X21 | W21 | W22 | - | V11
LAB | L83 | L84 | L85 | L86 | L87 | L88 | Lunch | L89 | L90 | L91 | L92 | L93 | L94 | -

**IMAGE**
![Annotation 2024-01-05 082642](https://github.com/GDGVIT/vitty-app/assets/115636830/3a90b614-2ff4-47a8-ad6a-1464b9703b6e)

**Comment by dk-a-dev** [comment]
@MayankMangipudi the new update for VITTY is out for both ios and android, the update brings a new way to set your timetable!!! Update your app!!!
This issue will be marked as resolved!! 🤍

**Comment by dk-a-dev** [comment]
issue is reolved
