### ISSUE TITLE
Unrecognized course codes

### ISSUE THREAD

**Issue by sankalpmukim** [GDGVIT/vitty-app#8]
**Describe the bug**

**To Reproduce**
1. I used this picture
2. 
![image](https://user-images.githubusercontent.com/41541375/127769503-e8af0970-c01b-4e89-865a-a8c049b51c0a.png)
3. I got this result
4. 
![image](https://user-images.githubusercontent.com/41541375/127770107-2ef88192-9b50-488b-a157-5ee2153446a3.png)

**Expected behavior**
It should have read my image correctly and then as per course codes, shown course **names**.

**Environment**
I use the brave browser which uses Chromium engine.

**Possible solution**
Add even more customization (I appreciate the text edit method)

**Possible implementation**
If the course code is not readable, then display the whole Text that is written in that portion.

**Additional context**
There is several minor bugs as well.
 - It would be nice to have Faculty info as well
 - Why not integrate with Google Calendar api. This is a feature request I will put and happily implement if the other bugs are fixed and this is more usable.
 - This is a great app with some amazing features already as well as some potential more.

#### Is this is a critical security vulnerability?
- [ ] Yes: Please read code-of-conduct once
- [x] No

**Comment by BRO3886** [comment]
@sankalpmukim some feature improvements like calendar integration and faculty info have been planned and will be implemented later

As for the images, yes it's not always accurate, but you can edit the name or time on the extension itself. Also try pasting the timetable as text, it's pretty accurate.
